### ISSUE TITLE
Invalid for version 2.78.0 (current version)

### ISSUE THREAD

**Issue by Sfeeen** [makindotcc/McHttpFrida#1]
This interceptor is only valid for version 2.36.0 as your command indicates. 
If you are still working on this or want to work on this please get in touch

**Comment by makindotcc** [comment]
you need to update class names, because they are different in every build due to obfuscation techniques.

eg.
```js
const BridgeInterceptor = Java.use("com.r06"); // okhttp3.internal.http.BridgeInterceptor
```
https://github.com/square/okhttp/blob/8ebb4b1f9497db158019716195dda4b255edfe83/okhttp/src/main/kotlin/okhttp3/internal/http/BridgeInterceptor.kt#L53C32-L53C49
You can search for classes with string "Transfer-Encoding" in .apk and find similar one.

Personally now I would try to disable certificate pinning and attach Burp Suite proxy to phone.
This may work: https://github.com/httptoolkit/frida-interception-and-unpinning

**Comment by Sfeeen** [comment]
Thanks for you time and explanation, I'm actually aware of those aspects and have written similar Frida scripts myself. Unfortunately [shrinking](https://developer.android.com/build/shrink-code) seems to be more prone nowadays which sometimes causes trouble finding the right functions to use. 
FYOI The app makes use of [Certificate transparency](https://github.com/appmattus/certificatetransparency) now (actually for a while already).

The actual reason of my 'issue ' is to get in touch and see if you are still working on it and want to share your findings, if you want please accept me on discard, if you are busy now with other stuff that's fine as well :)
